### ISSUE TITLE
Sistema Sei não encontrado

### ISSUE THREAD

**Issue by rafaelfariasbsb** [anatelgovbr/mod-sei-peticionamento#80]
Estou fazendo a instalação na versão 4.1.2 do Sei e Versão Principal - v4.2.0
O script do sei roda sem problema nenhum
Ao rodar o script do sip aparece seguinte erro no log
/usr/bin/php -c /etc/php.ini /opt/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php 2>&1 > atualizacao_peticionamento_sip.log

log no sip
Descrição:
Sistema SEI não encontrado.

Mensagem:
Sistema SEI não encontrado.

Trilha de Processamento:
#0 /opt/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php(2338): InfraRN->__call()
#1 {main}

Trilha de Processamento Original:
0 /opt/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php(103): MdPetAtualizadorSipRN->instalarv001()
1 /opt/infra/infra_php/InfraRN.php(149): MdPetAtualizadorSipRN->atualizarVersaoConectado()
2 /opt/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php(2338): InfraRN->__call()
3 {main}

**Comment by rafaelfariasbsb** [comment]
segue o log completo

00001 - INICIANDO A INSTALA��O/ATUALIZA��O DO M�DULO DE PETICIONAMENTO E INTIMA��O ELETR�NICOS NO SIP VERS�O 3.1.2
00002 - [InfraMySqli->consultarSql] select lower(table_name) as table_name from information_schema.tables where lower(table_type) = 'base table' AND lower(table_schema)='sip' and lower(table_name)='sip_teste' order by table_name asc;
00003 - [InfraMySqli->consultarSql] 0 registro(s)
00004 - [InfraMySqli->consultarSql] 0.002 s
00005 - [InfraMySqli->executar] CREATE TABLE sip_teste (id integer null)
00006 - [InfraMySqli->executar] 0 registro(s) afetado(s)
00007 - [InfraMySqli->executar] 0.035 s
00008 - [InfraMySqli->executar] DROP TABLE sip_teste
00009 - [InfraMySqli->executar] 0 registro(s) afetado(s)
00010 - [InfraMySqli->executar] 0.019 s
00011 - [InfraParametro->getStrValor] VERSAO_MODULO_PETICIONAMENTO
00012 - [InfraRN->__call] InfraParametroRN.consultar
00013 - [InfraMySqli->consultarSql] SELECT infra_parametro.valor FROM infra_parametro WHERE infra_parametro.nome=?

Bind:
0: s, VERSAO_MODULO_PETICIONAMENTO

00014 - [InfraMySqli->consultarSql] 0 registro(s)
00015 - [InfraMySqli->consultarSql] 0 s
00016 - EXECUTANDO A INSTALA��O/ATUALIZA��O DA VERS�O 0.0.1 DO M�DULO DE PETICIONAMENTO E INTIMA��O ELETR�NICOS NA BASE DO SIP
00017 - [InfraRN->__call] SistemaRN.consultar
00018 - [InfraMySqli->consultarSql] SELECT sistema.id_sistema AS idsistema FROM sistema WHERE sistema.sigla=? AND sistema.sin_ativo=?

Bind:
0: s, SEI
1: s, S

00019 - [InfraMySqli->consultarSql] 0 registro(s)
00020 - [InfraMySqli->consultarSql] 0 s
Descri��o:
Sistema SEI n�o encontrado.

Mensagem:
Sistema SEI n�o encontrado.

Trilha de Processamento:
#0 /opt/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php(2338): InfraRN->__call()
#1 {main}

Trilha de Processamento Original:
\n0 /opt/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php(103): MdPetAtualizadorSipRN->instalarv001()
\n1 /opt/infra/infra_php/InfraRN.php(149): MdPetAtualizadorSipRN->atualizarVersaoConectado()
\n2 /opt/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php(2338): InfraRN->__call()
\n3 {main}

00021 - [InfraRN->__call] LogSip.gravar
00022 - [InfraMySqli->abrirTransacao] InfraMySqli-localhost-3306-sip-root
00023 - [InfraMySqli->executar] INSERT INTO seq_infra_log (campo) VALUES ('0')
00024 - [InfraMySqli->executar] 1 registro(s) afetado(s)
00025 - [InfraMySqli->executar] 0 s
00026 - [InfraRN->__call] InfraLogRN.cadastrar
00027 - [InfraMySqli->executar] INSERT INTO infra_log (id_infra_log,ip,dth_log,sta_tipo,texto_log) VALUES (?,?,?,?,?)

Bind:
0: i, 31683
1: s, 
2: s, 2024-11-01 09:56:37
3: s, E
4: s, Descri��o:
Sistema SEI n�o encontrado.

Mensagem:
Sistema SEI n�o encontrado.

Trilha de Processamento:
#0 /opt/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php(2338): InfraRN->__call()
#1 {main}

Trilha de Processamento Original:
\n0 /opt/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php(103): MdPetAtualizadorSipRN->instalarv001()
\n1 /opt/infra/infra_php/InfraRN.php(149): MdPetAtualizadorSipRN->atualizarVersaoConectado()
\n2 /opt/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php(2338): InfraRN->__call()
\n3 {main}

00028 - [InfraMySqli->executar] 1 registro(s) afetado(s)
00029 - [InfraMySqli->executar] 0.002 s
00030 - [InfraMySqli->confirmarTransacao] InfraMySqli-localhost-3306-sip-root
00031 - [InfraMySqli->fecharConexao] InfraMySqli-localhost-3306-sip-root

**Comment by rafaelfariasbsb** [comment]
precisava mudar o nome do da sigla do SEI
